# Generated by Django 5.0.4 on 2024-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('EUA', 'USA'), ('BRA', 'Brazil'), ('FRANCE', 'France'), ('ISR', 'Israel'), ('CHI', 'China'), ('SKR', 'South Korea'), ('ITA', 'Italy'), ('CAN', 'Canada'), ('AUS', 'Australia'), ('UK', 'UK')], max_length=100)),
            ],
        ),
    ]
